version: '3.8'

services:
  blog:
    build: .
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - ./posts:/app/posts:ro  # Mount blog posts as read-only
    networks:
      - blog-network

  # Optional: Add nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # If using SSL certificates
    depends_on:
      - blog
    restart: unless-stopped
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge
